import KeyEvent from './android/KeyEvent';

export const KeyEventToChar = new Map<number, string>([
    [KeyEvent.KEYCODE_0, '0'],
    [KeyEvent.KEYCODE_1, '1'],
    [KeyEvent.KEYCODE_2, '2'],
    [KeyEvent.KEYCODE_3, '3'],
    [KeyEvent.KEYCODE_4, '4'],
    [KeyEvent.KEYCODE_5, '5'],
    [KeyEvent.KEYCODE_6, '6'],
    [KeyEvent.KEYCODE_7, '7'],
    [KeyEvent.KEYCODE_8, '8'],
    [KeyEvent.KEYCODE_9, '9'],
    [KeyEvent.KEYCODE_A, 'a'],
    [KeyEvent.KEYCODE_B, 'b'],
    [KeyEvent.KEYCODE_C, 'c'],
    [KeyEvent.KEYCODE_D, 'd'],
    [KeyEvent.KEYCODE_E, 'e'],
    [KeyEvent.KEYCODE_F, 'f'],
    [KeyEvent.KEYCODE_G, 'g'],
    [KeyEvent.KEYCODE_H, 'h'],
    [KeyEvent.KEYCODE_I, 'i'],
    [KeyEvent.KEYCODE_J, 'j'],
    [KeyEvent.KEYCODE_K, 'k'],
    [KeyEvent.KEYCODE_L, 'l'],
    [KeyEvent.KEYCODE_M, 'm'],
    [KeyEvent.KEYCODE_N, 'n'],
    [KeyEvent.KEYCODE_O, 'o'],
    [KeyEvent.KEYCODE_P, 'p'],
    [KeyEvent.KEYCODE_Q, 'q'],
    [KeyEvent.KEYCODE_R, 'r'],
    [KeyEvent.KEYCODE_S, 's'],
    [KeyEvent.KEYCODE_T, 't'],
    [KeyEvent.KEYCODE_U, 'u'],
    [KeyEvent.KEYCODE_V, 'v'],
    [KeyEvent.KEYCODE_W, 'w'],
    [KeyEvent.KEYCODE_X, 'x'],
    [KeyEvent.KEYCODE_Y, 'y'],
    [KeyEvent.KEYCODE_Z, 'z'],
    [KeyEvent.KEYCODE_GRAVE, '`'],
    [KeyEvent.KEYCODE_MINUS, '-'],
    [KeyEvent.KEYCODE_EQUALS, '='],
    [KeyEvent.KEYCODE_LEFT_BRACKET, '['],
    [KeyEvent.KEYCODE_RIGHT_BRACKET, ']'],
    [KeyEvent.KEYCODE_BACKSLASH, '\\'],
    [KeyEvent.KEYCODE_SEMICOLON, ';'],
    [KeyEvent.KEYCODE_APOSTROPHE, '\''],
    [KeyEvent.KEYCODE_COMMA, ','],
    [KeyEvent.KEYCODE_PERIOD, '.'],
    [KeyEvent.KEYCODE_SLASH, '/'],
    [KeyEvent.KEYCODE_SPACE, ' '],
]);

export const KeyEventToCharUnderShift = new Map<number, string>([
    [KeyEvent.KEYCODE_0, ')'],
    [KeyEvent.KEYCODE_1, '!'],
    [KeyEvent.KEYCODE_2, '@'],
    [KeyEvent.KEYCODE_3, '#'],
    [KeyEvent.KEYCODE_4, '$'],
    [KeyEvent.KEYCODE_5, '%'],
    [KeyEvent.KEYCODE_6, '^'],
    [KeyEvent.KEYCODE_7, '&'],
    [KeyEvent.KEYCODE_8, '*'],
    [KeyEvent.KEYCODE_9, '('],
    [KeyEvent.KEYCODE_A, 'A'],
    [KeyEvent.KEYCODE_B, 'B'],
    [KeyEvent.KEYCODE_C, 'C'],
    [KeyEvent.KEYCODE_D, 'D'],
    [KeyEvent.KEYCODE_E, 'E'],
    [KeyEvent.KEYCODE_F, 'F'],
    [KeyEvent.KEYCODE_G, 'G'],
    [KeyEvent.KEYCODE_H, 'H'],
    [KeyEvent.KEYCODE_I, 'I'],
    [KeyEvent.KEYCODE_J, 'J'],
    [KeyEvent.KEYCODE_K, 'K'],
    [KeyEvent.KEYCODE_L, 'L'],
    [KeyEvent.KEYCODE_M, 'M'],
    [KeyEvent.KEYCODE_N, 'N'],
    [KeyEvent.KEYCODE_O, 'O'],
    [KeyEvent.KEYCODE_P, 'P'],
    [KeyEvent.KEYCODE_Q, 'Q'],
    [KeyEvent.KEYCODE_R, 'R'],
    [KeyEvent.KEYCODE_S, 'S'],
    [KeyEvent.KEYCODE_T, 'T'],
    [KeyEvent.KEYCODE_U, 'U'],
    [KeyEvent.KEYCODE_V, 'V'],
    [KeyEvent.KEYCODE_W, 'W'],
    [KeyEvent.KEYCODE_X, 'X'],
    [KeyEvent.KEYCODE_Y, 'Y'],
    [KeyEvent.KEYCODE_Z, 'Z'],
    [KeyEvent.KEYCODE_GRAVE, '~'],
    [KeyEvent.KEYCODE_MINUS, '_'],
    [KeyEvent.KEYCODE_EQUALS, '+'],
    [KeyEvent.KEYCODE_LEFT_BRACKET, '{'],
    [KeyEvent.KEYCODE_RIGHT_BRACKET, '}'],
    [KeyEvent.KEYCODE_BACKSLASH, '|'],
    [KeyEvent.KEYCODE_SEMICOLON, ':'],
    [KeyEvent.KEYCODE_APOSTROPHE, '"'],
    [KeyEvent.KEYCODE_COMMA, '<'],
    [KeyEvent.KEYCODE_PERIOD, '>'],
    [KeyEvent.KEYCODE_SLASH, '?'],
]);

export const KeyEventSpecial = new Map<number, string>([]);